// DO NOT EDIT! THIS IS GENERATED FILE

export const mapping = {
  admRefreshTokens: 'AdmRefreshToken',
  appLogins: 'AppLogin',
  appRefreshTokens: 'AppRefreshToken',
  auditLogActionTypes: 'AuditLogActionType',
  auditLogs: 'AuditLog',
  autogenerationHistoryEntries: 'AutogenerationHistoryEntry',
  autogenerationRules: 'AutogenerationRule',
  delegations: 'Delegation',
  entities: 'Entity',
  files: 'File',
  languages: 'Language',
  managerLogins: 'ManagerLogin',
  managers: 'Manager',
  managersToPermissions: 'ManagersToPermission',
  managersToRoles: 'ManagersToRole',
  messageTemplates: 'MessageTemplate',
  messageTypes: 'MessageType',
  permissions: 'Permission',
  roles: 'Role',
  rolesToPermissions: 'RolesToPermission',
  stats: 'Stat',
  tags: 'Tag',
  units: 'Unit',
  users: 'User',
};
